package rules;

import com.address.model.*;

dialect "mvel"

rule "Monaco zipcode"
  when
    propuesta : Propuesta()
    address:Address(zipcode == "90185" && pais == "Monaco")
  then
    propuesta.setValoracion(100L);
    propuesta.setPropuesta(null);
end

rule "Monaco zipcode wrong"
  when
    propuesta : Propuesta()
    address:Address(zipcode != "90185" && pais == "Monaco")
  then
    propuesta.setValoracion(0L);
    propuesta.setPropuesta("90185");
end